load "scripts/split_toggl_midnight_timers.rb"
load "scripts/send_toggl_to_calendar.rb"
load "scripts/populate_calendar.rb"
load "scripts/daily_creative_report.rb"
load "scripts/daily_work_report.rb"
load "scripts/daily_trends_data_export.rb"
