require_relative "../libs/toggl/report"
require_relative "../libs/toggl/google_calendar_adapter"
require_relative "../libs/summaries/daily"
require_relative "../libs/activities/log"
require_relative "../date_time_helper"
require "time"
